language: android
jdk:
  - oraclejdk8

# To avoid following similar issues:
# * https://github.com/travis-ci/travis-ci/issues/5582
# * https://github.com/OneBusAway/onebusaway-android/pull/476
sudo: true

android:
  components:
    # Use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-25.0.2

    # The SDK version used to compile your project
    - android-25

    # Additional components
    - extra-android-m2repository
    - extra-google-m2repository

script:
  ./gradlew clean build
